#!/usr/bin/env python3
"""Patch 30: sampled audio for the anvil and the campfire bed.

Until now every sound in Grim World was synthesised at runtime, which is a real
strength: nothing to download and no sound ever repeats. It has one blind spot.
Metal and fire are the two things oscillators are worst at. A struck anvil is
six inharmonic partials all decaying at different rates; a fire is broadband
noise that never repeats. Synthesis gets close enough that you notice it is
only close.

So four sounds become samples and everything else stays synthesised:

  anvil-strike   the main blow, 1.55s ring
  anvil-ring     longer sustain, brighter, for variety between blows
  anvil-dead     a dull blow landing on HOT iron, which absorbs the energy
  fire-bed       a true seamless loop carrying the flame roar

The campfire keeps its procedural crackle layered ON TOP of the sampled bed.
That is not a hedge. Pops are exactly the element the ear tracks for
repetition, and the procedural ones never repeat, while the steady roar
underneath is what a sample nails and synthesis struggles with. Each fire also
starts the loop at a random offset so two fires in view never phase together.

Generated FROM model-lab/sfx-samples.js, which is itself generated by
harness/sfx.py from the ElevenLabs text-to-sound-effects endpoint. Nothing is
retyped.

Cost: 220 KB of base64 on a 1574 KB bundle, about +14%. That was the number
Kevin approved, arrived at by trimming each clip to where it actually stops and
matching bitrate to content (96k tonal metal, 64k broadband fire).

Three anchored edits:
  1. the samples and the player, plus creation inside audioInit
  2. anvilStrike, off the synthesised kit and onto the samples
  3. the campfire voice, so the sampled bed rides under the procedural crackle
"""
import io, os, re

SRC = '/tmp/game-src.html'
HERE = os.path.dirname(__file__)
MODULE = os.path.join(HERE, '..', '..', 'model-lab', 'sfx-samples.js')

s = io.open(SRC, encoding='utf-8').read()
mod = io.open(MODULE, encoding='utf-8').read()

assert 'export const SFX_SAMPLES' in mod, 'sample module entry point moved'
body = re.sub(r'^export ', '', mod, flags=re.M)
body = re.sub(r'\A// GRIM WORLD: sampled sound effects\.\n(//.*\n)*\n', '', body)
body = '\n'.join(('    ' + ln) if ln.strip() else '' for ln in body.split('\n'))

# ---------------------------------------------------------------------------
# 1. the samples, the player, and the hook in audioInit
# ---------------------------------------------------------------------------
# audioInit runs on the first user gesture, which is the earliest an
# AudioContext is allowed to exist at all, so it is also the earliest we can
# decode. decodeAudioData is async: the first anvil blow of a session can land
# before it resolves. Every caller checks and falls back to the synthesised
# voice, so a slow decode costs one slightly different blow, never silence.
A1 = """    this.noiseBuf = buf;
  }"""
assert s.count(A1) == 1, 'audioInit anchor matched %d times' % s.count(A1)
s = s.replace(A1, """    this.noiseBuf = buf;
    this.sampleInit();
  }

  // ---- sampled audio -------------------------------------------------------
  // Built from model-lab/sfx-samples.js by harness/patches/30_sfx_samples.py.
  // Do not hand-edit the blobs: regenerate with harness/sfx.py and rebuild.
  sampleInit() {
    if (this._samples || !this.ac) return;
""" + body + """
    try {
      this._samples = makeSamplePlayer(this.ac, this.master, SFX_SAMPLES);
    } catch (e) {
      // A browser that cannot decode our mp3 must not take the whole game
      // down with it. Everything below falls back to the synthesised voice.
      this._samples = null;
    }
  }""")

# ---------------------------------------------------------------------------
# 2. the anvil
# ---------------------------------------------------------------------------
A2 = """    const kit = this._anvilKit;
    if (!kit || !kit.strike) { this.sfx('block'); return; }
    kit.strike(this.ac, this.master, { gain: 0.5, heavy: !!heavy });"""
assert s.count(A2) == 1, 'anvilStrike anchor matched %d times' % s.count(A2)
s = s.replace(A2, """    const S = this._samples;
    if (S && S.ready()) {
      // A blow on hot iron is DULLER than one on the bare face, because the
      // billet absorbs the energy. The forge alternates so a heat sounds like
      // work being done rather than a button being pressed.
      this._forgeAlt = (this._forgeAlt || 0) + 1;
      const name = heavy ? 'anvil-dead'
        : (this._forgeAlt % 3 === 0 ? 'anvil-ring' : 'anvil-strike');
      if (S.has(name)) {
        // Detune every blow. Four identical clangs is the sound of a sample
        // being retriggered, and it is the one thing the synthesised version
        // got right for free.
        const cents = -45 + Math.random() * 90;
        S.play(name, { gain: heavy ? 0.62 : 0.5, detune: cents });
        return;
      }
    }
    const kit = this._anvilKit;
    if (!kit || !kit.strike) { this.sfx('block'); return; }
    kit.strike(this.ac, this.master, { gain: 0.5, heavy: !!heavy });""")

# ---------------------------------------------------------------------------
# 3. the campfire voice
# ---------------------------------------------------------------------------
A3 = """        f.snd = f.kit.sound(this.ac, this.master, { gain: 0.5 });"""
assert s.count(A3) == 1, 'campfire sound anchor matched %d times' % s.count(A3)
s = s.replace(A3, """        f.snd = this.campfireVoice(f.kit, 0.5);""")

# Put the composite voice next to the thing that uses it.
A4 = """  // One uniform for every flame in the world, plus a gentle breath on the pool"""
assert s.count(A4) == 1, 'campfire tick anchor matched %d times' % s.count(A4)
s = s.replace(A4, """  // The sampled flame roar with the procedural crackle riding on top. Both
  // respond to distance together, so from the caller's side this is the same
  // { stop, setDistance } object f.kit.sound used to return.
  campfireVoice(kit, gain) {
    // The procedural voice drops to 0.55 because the sampled bed now carries
    // the body. Its crackles come down with it, which is the trade: what they
    // are here for is variety, not level.
    const proc = kit.sound(this.ac, this.master, { gain: gain * 0.55 });
    let bed = null;
    const S = this._samples;
    if (S && S.ready() && S.has('fire-bed')) {
      // Random start offset and a touch of rate drift, so two fires in view
      // never phase into one another and no single fire announces its loop.
      const buf = S.play('fire-bed', {
        gain: 0, loop: true, detune: -30 + Math.random() * 60
      });
      if (buf) {
        try { buf.src.loopStart = 0; buf.src.loopEnd = 0; } catch (e) {}
        bed = buf;
      }
    }
    return {
      stop: function () {
        proc.stop();
        if (bed) { try { bed.src.stop(); } catch (e) {} }
      },
      setDistance: function (d, gone) {
        proc.setDistance(d, gone);
        if (bed) {
          const f = Math.max(0, 1 - d / gone);
          bed.gain.gain.value = gain * 0.9 * f * f;
        }
      }
    };
  }

""" + A4)

io.open(SRC, 'w', encoding='utf-8').write(s)
print('patch 30: sampled audio installed (%d bytes of module inlined)' % len(body))
